apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: kubernetes-version-exporter
  labels:
    {{- .Values.labels | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- .Values.labels | toYaml | nindent 6 }}
  podMetricsEndpoints:
  - port: http